apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
  namespace: traderx
data:
  nats.conf: |
    port: 4222
    http: 8222

    websocket {
      port: 8081
      no_tls: true
    }

    jetstream {
      store_dir: /data/jetstream
      max_memory_store: 512MB
      max_file_store: 4GB
    }
