port: 4222

http_port: 8222

websocket {
  port: 8081
  no_tls: true
  same_origin: false
}

no_auth_user: runtime

authorization {
  users: [
    {
      user: runtime
      password: runtime-local
      permissions: {
        publish: { allow: [">"], deny: ["traderx.control.>"] }
        subscribe: { allow: [">"], deny: ["traderx.control.>"] }
      }
    }
    {
      user: control-source
      password: control-source-local
      permissions: {
        publish: ["traderx.control.>"]
        subscribe: ["_INBOX.>"]
      }
    }
    {
      user: order-matcher
      password: order-matcher-local
      permissions: {
        publish: { allow: [">"], deny: ["traderx.control.>"] }
        subscribe: [">"]
      }
    }
  ]
}

jetstream {
  store_dir: "/data/jetstream"
  max_memory_store: 256MB
  max_file_store: 1GB
}
