apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: traderx-ingress
  namespace: traderx
spec:
  ingressClassName: nginx
  rules:
  - host: yaakovseif.dev
    http:
      paths:
      - backend:
          service:
            name: edge-proxy
            port:
              number: 8080
        path: /
        pathType: Prefix
  - host: grafana.yaakovseif.dev
    http:
      paths:
      - backend:
          service:
            name: grafana
            port:
              number: 3000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - yaakovseif.dev
    - grafana.yaakovseif.dev
    secretName: yaakovseif-dev-tls
