package finos.traderx.accountservice.repository;

import finos.traderx.accountservice.model.AccountControlEvent;
import java.util.List;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

@Repository
public class AccountControlEventRepository {
  private final JdbcTemplate jdbc;

  public AccountControlEventRepository(JdbcTemplate jdbc) {
    this.jdbc = jdbc;
    jdbc.execute("create table if not exists AccountControlOutbox ("
        + "Version bigint generated by default as identity primary key, SourceEpoch bigint not null, "
        + "EventType varchar(32) default 'ACCOUNT' not null, AccountId integer not null, "
        + "Principal varchar(128), Enabled boolean not null, SourceTimeMillis bigint not null, "
        + "Published boolean default false not null)");
    jdbc.execute("alter table AccountControlOutbox add column if not exists "
        + "EventType varchar(32) default 'ACCOUNT' not null");
    jdbc.execute("alter table AccountControlOutbox add column if not exists Principal varchar(128)");
    jdbc.execute("alter table AccountControlOutbox add column if not exists "
        + "Published boolean default false not null");
  }

  public void append(long epoch, String eventType, int accountId, String principal, boolean enabled,
                     long sourceTimeMillis) {
    jdbc.update("insert into AccountControlOutbox "
        + "(SourceEpoch, EventType, AccountId, Principal, Enabled, SourceTimeMillis) "
        + "values (?, ?, ?, ?, ?, ?)", epoch, eventType, accountId, principal, enabled,
        sourceTimeMillis);
  }

  public long watermark() {
    Long value = jdbc.queryForObject("select coalesce(max(Version), 0) from AccountControlOutbox", Long.class);
    return value == null ? 0L : value;
  }

  public List<AccountControlEvent> after(long version) {
    return jdbc.query("select Version, SourceEpoch, EventType, AccountId, Principal, Enabled, SourceTimeMillis "
        + "from AccountControlOutbox where Version > ? order by Version", (rs, row) ->
        new AccountControlEvent(rs.getLong(1), rs.getLong(2), rs.getString(3), rs.getInt(4),
            rs.getString(5), rs.getBoolean(6), rs.getLong(7)), version);
  }

  public List<AccountControlEvent> unpublished(int limit) {
    return jdbc.query("select Version, SourceEpoch, EventType, AccountId, Principal, Enabled, SourceTimeMillis "
        + "from AccountControlOutbox where Published = false order by Version limit ?", (rs, row) ->
        new AccountControlEvent(rs.getLong(1), rs.getLong(2), rs.getString(3), rs.getInt(4),
            rs.getString(5), rs.getBoolean(6), rs.getLong(7)), limit);
  }

  public void markPublished(long version) {
    jdbc.update("update AccountControlOutbox set Published = true where Version = ?", version);
  }
}
