package finos.traderx.accountservice.repository;

import finos.traderx.accountservice.model.RiskControlEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

/** Transactional authoritative risk-control state and outbox. */
@Repository
public class RiskControlEventRepository {
  private final JdbcTemplate jdbc;

  public RiskControlEventRepository(JdbcTemplate jdbc) {
    this.jdbc = jdbc;
    jdbc.execute("create table if not exists RiskControlOutbox ("
        + "Version bigint generated by default as identity primary key, SourceEpoch bigint not null, "
        + "EventType varchar(32) not null, AggregateKey varchar(128) not null, Enabled boolean not null, "
        + "PolicyVersion bigint not null, MaxPositionQuantity integer not null, "
        + "MaxConcentrationNotionalTicks bigint not null, OperatorId varchar(128) not null, "
        + "SourceTimeMillis bigint not null, Published boolean default false not null)");
    jdbc.execute("create table if not exists RiskControlState ("
        + "EventType varchar(32) not null, AggregateKey varchar(128) not null, Version bigint not null, "
        + "SourceEpoch bigint not null, Enabled boolean not null, PolicyVersion bigint not null, "
        + "MaxPositionQuantity integer not null, MaxConcentrationNotionalTicks bigint not null, "
        + "OperatorId varchar(128) not null, SourceTimeMillis bigint not null, "
        + "primary key (EventType, AggregateKey))");
  }

  public long currentVersion(String eventType, String aggregateKey) {
    List<Long> versions = jdbc.query("select Version from RiskControlState where EventType=? and AggregateKey=?",
        (rs, row) -> rs.getLong(1), eventType, aggregateKey);
    return versions.isEmpty() ? 0L : versions.getFirst();
  }

  public long append(long epoch, String eventType, String aggregateKey, boolean enabled,
                     long policyVersion, int maxPositionQuantity,
                     long maxConcentrationNotionalTicks, String operator, long sourceTimeMillis) {
    Long version = jdbc.queryForObject("insert into RiskControlOutbox "
            + "(SourceEpoch,EventType,AggregateKey,Enabled,PolicyVersion,MaxPositionQuantity,"
            + "MaxConcentrationNotionalTicks,OperatorId,SourceTimeMillis) values (?,?,?,?,?,?,?,?,?) "
            + "returning Version", Long.class, epoch, eventType, aggregateKey, enabled, policyVersion,
        maxPositionQuantity, maxConcentrationNotionalTicks, operator, sourceTimeMillis);
    long assigned = version == null ? 0L : version;
    jdbc.update("insert into RiskControlState "
            + "(EventType,AggregateKey,Version,SourceEpoch,Enabled,PolicyVersion,MaxPositionQuantity,"
            + "MaxConcentrationNotionalTicks,OperatorId,SourceTimeMillis) values (?,?,?,?,?,?,?,?,?,?) "
            + "on conflict (EventType,AggregateKey) do update set Version=excluded.Version,"
            + "SourceEpoch=excluded.SourceEpoch,Enabled=excluded.Enabled,PolicyVersion=excluded.PolicyVersion,"
            + "MaxPositionQuantity=excluded.MaxPositionQuantity,"
            + "MaxConcentrationNotionalTicks=excluded.MaxConcentrationNotionalTicks,"
            + "OperatorId=excluded.OperatorId,SourceTimeMillis=excluded.SourceTimeMillis",
        eventType, aggregateKey, assigned, epoch, enabled, policyVersion, maxPositionQuantity,
        maxConcentrationNotionalTicks, operator, sourceTimeMillis);
    return assigned;
  }

  public long watermark() {
    Long value = jdbc.queryForObject("select coalesce(max(Version),0) from RiskControlOutbox", Long.class);
    return value == null ? 0L : value;
  }

  public List<RiskControlEvent> state() {
    return jdbc.query("select Version,SourceEpoch,EventType,AggregateKey,Enabled,PolicyVersion,"
        + "MaxPositionQuantity,MaxConcentrationNotionalTicks,OperatorId,SourceTimeMillis "
        + "from RiskControlState order by EventType,AggregateKey", this::map);
  }

  public List<RiskControlEvent> after(long version) {
    return jdbc.query("select Version,SourceEpoch,EventType,AggregateKey,Enabled,PolicyVersion,"
        + "MaxPositionQuantity,MaxConcentrationNotionalTicks,OperatorId,SourceTimeMillis "
        + "from RiskControlOutbox where Version>? order by Version", this::map, version);
  }

  public List<RiskControlEvent> unpublished(int limit) {
    return jdbc.query("select Version,SourceEpoch,EventType,AggregateKey,Enabled,PolicyVersion,"
        + "MaxPositionQuantity,MaxConcentrationNotionalTicks,OperatorId,SourceTimeMillis "
        + "from RiskControlOutbox where Published=false order by Version limit ?", this::map, limit);
  }

  public void markPublished(long version) {
    jdbc.update("update RiskControlOutbox set Published=true where Version=?", version);
  }

  private RiskControlEvent map(ResultSet rs, int row) throws SQLException {
    return new RiskControlEvent(rs.getLong(1), rs.getLong(2), rs.getString(3), rs.getString(4),
        rs.getBoolean(5), rs.getLong(6), rs.getInt(7), rs.getLong(8), rs.getString(9), rs.getLong(10));
  }
}
