apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: order-matcher
  namespace: traderx
spec:
  replicas: 2
  template:
    spec:
      nodeSelector: null
      tolerations: null
      containers:
        - name: order-matcher
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "500m"
              memory: 1Gi
            limits:
              memory: 2Gi
          env:
            - name: BLP_REPLICATION_ENABLED
              value: "true"
            - name: BLP_REPLICATION_TRANSPORT
              value: "aeron"
        - name: aeron-replication-sidecar
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "100m"
              memory: 128Mi
            limits:
              cpu: "500m"
              memory: 256Mi
